//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UGM_ERPEntities : DbContext
    {
        public UGM_ERPEntities()
            : base("name=UGM_ERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        internal object Assan_Fatura_Text()
        {
            throw new NotImplementedException();
        }

        public virtual ObjectResult<string> Assan_Dekont_Text(string dekontNo, Nullable<int> dekontYil, Nullable<int> musteriNo)
        {
            var dekontNoParameter = dekontNo != null ?
                new ObjectParameter("DekontNo", dekontNo) :
                new ObjectParameter("DekontNo", typeof(string));
    
            var dekontYilParameter = dekontYil.HasValue ?
                new ObjectParameter("DekontYil", dekontYil) :
                new ObjectParameter("DekontYil", typeof(int));
    
            var musteriNoParameter = musteriNo.HasValue ?
                new ObjectParameter("MusteriNo", musteriNo) :
                new ObjectParameter("MusteriNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Assan_Dekont_Text", dekontNoParameter, dekontYilParameter, musteriNoParameter);
        }
    
        public virtual ObjectResult<string> Assan_Fatura_Text(string faturaNo, Nullable<int> faturaYil, Nullable<int> musteriNo)
        {
            var faturaNoParameter = faturaNo != null ?
                new ObjectParameter("FaturaNo", faturaNo) :
                new ObjectParameter("FaturaNo", typeof(string));
    
            var faturaYilParameter = faturaYil.HasValue ?
                new ObjectParameter("FaturaYil", faturaYil) :
                new ObjectParameter("FaturaYil", typeof(int));
    
            var musteriNoParameter = musteriNo.HasValue ?
                new ObjectParameter("MusteriNo", musteriNo) :
                new ObjectParameter("MusteriNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Assan_Fatura_Text", faturaNoParameter, faturaYilParameter, musteriNoParameter);
        }
    }
}
